# Generated by Django 5.2.1 on 2025-05-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="created_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="email",
            name="date_at",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="email",
            name="time_at",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_at",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="time_at",
            field=models.TimeField(),
        ),
    ]
